### PR TITLE
Make :mod:`PySide2` not fail

### LINKED ISSUE #13: Referencing the top level module fails - :mod:`PySide2`
https://github.com/Czaki/sphinx-qt-documentation/blob/25d2dc15fb14a3b2b2ab45de889c2e0eabb76cd4/sphinx_qt_documentation/__init__.py#L94

```pytb
Traceback (most recent call last):
  File "/epc/repos/ssst/venv/lib/python3.9/site-packages/sphinx/events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "/epc/repos/ssst/venv/lib/python3.9/site-packages/sphinx_qt_documentation/__init__.py", line 94, in missing_reference
    head, tail = target.split(".", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

This shows up cryptically through Sphinx as follows.

```
Extension error:
Handler <function missing_reference at 0x7efbfce2d1f0> for event 'missing-reference' threw an exception (exception: not enough values to unpack (expected 2, got 1))
```

### PR DESCRIPTION
**Pull request by altendky**
Fixes #13

Draft for:
- [ ] It doesn't fail now but I haven't verified an actual working link.

### CODE REVIEW

**Comment by altendky** [comment]
Yep, neither PyQt5 nor PySide2 end up with functioning links.

**Comment by Czaki** [comment]
If its ready please change on ready for review.

**Comment by altendky** [comment]
It avoids the exception, so perhaps it is a useful step.  But, it doesn't actually create working links.  If you like the step, I guess it's just as well to split it up.

**Comment by Czaki** [comment]
Sorry for long delay.

**Comment by altendky** [comment]
Heh, no worries.  I've got plenty of backlog to get through myself...

**Pull request merged**
